[project]
name = 'Decentralized-Digital-Identity-for-Banking'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.consent-management]
path = 'contracts/consent-management.clar'
clarity_version = 2
epoch = 2.5

[contracts.fraud-prevention]
path = 'contracts/fraud-prevention.clar'
clarity_version = 2
epoch = 2.5

[contracts.identity-verification]
path = 'contracts/identity-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.kyc-documentation]
path = 'contracts/kyc-documentation.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
